export const FETCH_PLANETS = 'FETCH_PLANETS';
export const FILTER_BY_NAME = 'FILTER_BY_NAME';
export const FILTER_BY_COLUMN = 'FILTER_BY_COLUMN';
export const FILTER_BY_COMPARISON = 'FILTER_BY_COMPARISON';
export const FILTER_BY_VALUE = 'FILTER_BY_VALUE';
export const FILTER_BY_NUMBERS = 'FILTER_BY_NUMBERS';
